### ISSUE TITLE
Journey crossing Lng 180 (dateline) goes the long way round

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/TLCMapViews#11]
If you make a journey where the ship crosses 180 latitude, around where the international date line is in the middle of the Pacific, the line suddenly goes the long way around the earth to join the dots, instead of the short direct route. Eg: if it went from 15.000,179.999 to 15.000,-179.999 it would be a line all around the world at lat 15.000.
The line of course should go the short way across 180/-180lng.
This is happening a lot with European exploratory ships journeys.
Might be something to do with the options 'wrapAround180:true' that can be set on a map, though that might only effect the 2d view, not drawing a line on 3d, worth a look though: https://geodienste-umwelt.hessen.de/arcgis_js_api/sdk_37/jssamples/map_wraparound.html

Attached is an example of a ships journey.
[Crossing180_TLCMLayer_299.CSV](https://github.com/HughCraig/GHAP/files/9875912/Crossing180_TLCMLayer_299.CSV)

**Comment by IanMcCrabb** [comment]
If setting change works the OK otherwise push off till later

**Comment by yangli0516** [comment]
The documentation link above seems like an older version, and the option isn't available in the last version of ArcGIS JS library we are using. Haven't got any obvious solution after the research as I'm not a geographic expert.

However, one possible way is to calculate whether the shorter route crosses the date line. If it does, we create a middle point at the date line to enable the route travelling across the date line.

**Comment by HughCraig** [comment]
Maybe we need a GIS expert for this.

**Comment by BillPascoe** [comment]
This looks like it might be to solve this problem: https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-support-normalizeUtils.html

**Comment by BillPascoe** [comment]
Another approach may be as described here:
https://community.esri.com/t5/net-maps-sdk-questions/polyline-not-crossing-international-dateline/td-p/496299
which says that if crossing the line you should go greater than 180. Eg: going from 179 to -179 you could put 179 to 181 instead. Could see if this works, as it's an old suggestion, but in any case it's ugly in terms of having to run a lot of calculations to check for cases going to and from in each direction etc.

**Comment by BillPascoe** [comment]
Here is an actual working example of a fix: 
https://codepen.io/andygup/pen/QeyerP
( and also a more elaborate example of the same thing: https://jsbin.com/xegicih/2/edit?html,output )


<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="initial-scale=1,maximum-scale=1,user-scalable=no"
    />
    <title>Intro to graphics</title>

    <link
      rel="stylesheet"
      href="https://js.arcgis.com/4.20/esri/themes/light/main.css"
    />
    <script src="https://js.arcgis.com/4.20/"></script>

    <style>
      html,
      body,
      #viewDiv {
        padding: 0;
        margin: 0;
        height: 100%;
        width: 100%;
      }
    </style>

    <script>
      require([
          "esri/Map", 
          "esri/views/MapView", 
          "esri/Graphic", 
          "esri/geometry/Polyline", 
          "esri/geometry/support/geodesicUtils"], 
      (
        Map,
        MapView,
        Graphic, Polyline, geodesicUtils
      ) => {
        var map = new Map({
          basemap: "hybrid"
        });

        var view = new MapView({
          center: [-80, 35],
          container: "viewDiv",
          map: map,
          zoom: 2
        });

        /****************************
         * Create a polyline graphic
         ****************************/

        // First create a line geometry (this is the Keystone pipeline)
        var polyline = new Polyline({
          paths: [[138, 36], [-98, 49.5], [-118, 34], [-155.5828, 19.8968], [138, 36]]
        });

        // Create a symbol for drawing the line
        var lineSymbol = {
          type: "simple-line", // autocasts as SimpleLineSymbol()
          color: [226, 119, 40],
          width: 4
        };
        
        
        let g1 = null;
        let geom = geodesicUtils.geodesicDensify(polyline, 1000000);
        g1 = new Graphic({
          geometry: geom,
          symbol: lineSymbol
        })
              
        view.graphics.addMany([g1]);
        
      });
    </script>
  </head>

  <body>
    <div id="viewDiv"></div>
  </body>
</html>

**Comment by BillPascoe** [comment]
Please try again. This task was assigned back to Bill as there was no obvious fix that Yang or Bill could find at the time. Now it appears there might be some viable solutions to try out, so it can be re-allocated as part of a bug fix budget. Still a fairly high priority issue, as ships crossing the dateline suddenly zip all the way around the world, and user is asking questions about it.

**Comment by HughCraig** [comment]
From an email today: "There is one glitch with using TLCMap for our project.  At present the map will not construct routes that cross the 180 meridian (which mostly accords with the international dateline).  Our poor voyagers are forced to go the long way round the world, rather than being able to cross the Pacific.  It would be great to get that glitch ironed out before publicising our maps as it makes our maps cluttered and reduces a viewer’s ability to track where our ships are going."

**Comment by IanMcCrabb** [comment]
@MufengNiu can you prioritise this issue

**Comment by IanMcCrabb** [comment]
@MufengNiu can you update us on this one  I know you still had a known issue with the display of lines in 3D...

**Comment by HughCraig** [comment]
I am wondering where this one is up to. It still looks like a priority 1 bug.

**Comment by IanMcCrabb** [comment]
@HughCraig has assigned back to @BillPascoe as we had used up our September budget

**Comment by BillPascoe** [comment]
The available solutions don't appear to be using GeoJSON feeds as layers, so it may still be a bug with the ArcGIS JS API, but worth revisiting to see if a solution has arisen in the mean time, or if any of the suggested solutions can be made to apply, eg https://community.esri.com/t5/arcgis-javascript-maps-sdk-questions/polyline-not-crossing-the-international-dateline/td-p/565081

**Comment by IanMcCrabb** [comment]
@MufengNiu could you advise where we are on this and tag accordingly.

**Comment by MufengNiu** [comment]
I have identified a solution for this issue. It should be ready for merging after a final round of testing.

**Comment by yangli0516** [comment]
@MufengNiu, have you created the pull request for this one?

**Comment by BillPascoe** [comment]
@MufengNiu please provide a brief explanation of what the fix is. This was a very hard one to find an answer for. It would be good to have the knowledge base.

**Comment by HughCraig** [comment]
[Dateline bug.docx](https://github.com/HughCraig/TLCMapViews/files/13540711/Dateline.bug.docx)
I am thinking we could make this an item for the upcoming newsletter -- see attached file.

**Comment by MufengNiu** [comment]
@BillPascoe . We are currently utilizing the geodesicDensify() and normalizeCentralMeridian() functions, those are provided by ArcGIS which detects line crossing International dateline. If it does , we will break them at the IDL and reconstuct the journey line, it will only affect for lines crossing IDL while leaving other lines unaffected. 

Please see https://views.tlcmap.org/v2/journey.html?load=https%3A%2F%2Fghap.tlcmap.org%2Flayers%2F536%2Fjson%3Fline%3Droute. 
and https://test-views.tlcmap.org/v2.1/journey.html?load=https%3A%2F%2Ftest-ghap.tlcmap.org%2Flayers%2F1344%2Fjson%3Fline%3Droute for compatision.

**Comment by IanMcCrabb** [comment]
@MufengNiu if you might close this issue if its completed

**Comment by yangli0516** [comment]
There're some issues with the test server now. The server was automatically shut off and I wasn't able to restart the instance. Have lodged a ticket to Nectar support to address this. Please hold off testing this until we get the test server back running.

Related to https://github.com/HughCraig/GHAP/issues/340

**Comment by yangli0516** [comment]
This has been updated to the test site. Please test.
